name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_USER: test-user
    steps:
      - uses: actions/checkout@v4

      - name: Create user
        run: |
          sudo useradd -m $TEST_USER
          echo "ENVVAR='xyz'" | sudo tee /home/$TEST_USER/.bashrc

      - name: Test executing commands as user
        uses: ./
        with:
          commands: |
            whoami
            ls -al
            [[ $ENVVAR == "xyz" ]]
          user: $TEST_USER
          shell: bash
